/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacemenu;

import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author LENOVO
 */
public class MenuUtama extends javax.swing.JFrame {
    
    public void date (){
        Date ys = new Date();
        SimpleDateFormat s = new SimpleDateFormat("EEEEE, dd MM yyyy");
        date.setText(s.format(ys)); 
    }
    
    public MenuUtama() {
        initComponents();
        date();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnuser = new javax.swing.JButton();
        btnbarang = new javax.swing.JButton();
        btnkasir = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        btnreport = new javax.swing.JButton();
        btnsuppliers = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        date2 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        date1 = new javax.swing.JTextField();
        date3 = new javax.swing.JTextField();
        date4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfacemenu/icons8_NFT_User_120px.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dubai Medium", 2, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Owner");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, -1));

        jLabel12.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Inventory And Management");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 210, 50));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfacelogin/icons8_management_120px_3.png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 120, 120));

        jLabel14.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("I  M  A  N");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 150, 50));

        jLabel15.setFont(new java.awt.Font("Dubai Medium", 0, 25)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Marzuki Akmal");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnuser.setBackground(new java.awt.Color(255, 255, 255));
        btnuser.setForeground(new java.awt.Color(255, 255, 255));
        btnuser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfacemenu/icons8_user_folder_120px.png"))); // NOI18N
        btnuser.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 204, 255), new java.awt.Color(153, 204, 255)));
        btnuser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnuser.setOpaque(false);
        jPanel2.add(btnuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 140, 120));

        btnbarang.setBackground(new java.awt.Color(255, 255, 255));
        btnbarang.setForeground(new java.awt.Color(255, 255, 255));
        btnbarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfacemenu/icons8_shop_120px.png"))); // NOI18N
        btnbarang.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 204, 255), new java.awt.Color(153, 204, 255)));
        btnbarang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnbarang.setOpaque(false);
        jPanel2.add(btnbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 140, 120));

        btnkasir.setBackground(new java.awt.Color(255, 255, 255));
        btnkasir.setForeground(new java.awt.Color(255, 255, 255));
        btnkasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfacemenu/icons8_paper_money_120px.png"))); // NOI18N
        btnkasir.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 204, 255), new java.awt.Color(153, 204, 255)));
        btnkasir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnkasir.setOpaque(false);
        jPanel2.add(btnkasir, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 140, 120));

        btnlogout.setBackground(new java.awt.Color(255, 255, 255));
        btnlogout.setForeground(new java.awt.Color(255, 255, 255));
        btnlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfacemenu/icons8_exit_120px.png"))); // NOI18N
        btnlogout.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 204, 255), new java.awt.Color(153, 204, 255)));
        btnlogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlogout.setOpaque(false);
        jPanel2.add(btnlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 140, 120));

        btnreport.setBackground(new java.awt.Color(255, 255, 255));
        btnreport.setForeground(new java.awt.Color(255, 255, 255));
        btnreport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfacemenu/icons8_graph_report_120px.png"))); // NOI18N
        btnreport.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 204, 255), new java.awt.Color(153, 204, 255)));
        btnreport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnreport.setOpaque(false);
        jPanel2.add(btnreport, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 140, 120));

        btnsuppliers.setBackground(new java.awt.Color(255, 255, 255));
        btnsuppliers.setForeground(new java.awt.Color(255, 255, 255));
        btnsuppliers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfacemenu/icons8_supplier_120px.png"))); // NOI18N
        btnsuppliers.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 204, 255), new java.awt.Color(153, 204, 255)));
        btnsuppliers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsuppliers.setOpaque(false);
        jPanel2.add(btnsuppliers, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 140, 120));

        jLabel3.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        jLabel3.setText("Clock :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, 50, -1));

        date.setFont(new java.awt.Font("Dubai Medium", 0, 16)); // NOI18N
        date.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        date.setToolTipText("");
        date.setBorder(null);
        date.setCaretColor(new java.awt.Color(255, 255, 255));
        date.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        date.setEnabled(false);
        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });
        jPanel2.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 150, 40));

        jLabel5.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        jLabel5.setText("Date :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dubai Medium", 0, 18)); // NOI18N
        jLabel4.setText("User");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dubai Medium", 0, 18)); // NOI18N
        jLabel7.setText("Logout");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 320, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dubai Medium", 0, 18)); // NOI18N
        jLabel8.setText("Barang");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dubai Medium", 0, 18)); // NOI18N
        jLabel9.setText("Kasir");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));

        jLabel10.setFont(new java.awt.Font("Dubai Medium", 0, 18)); // NOI18N
        jLabel10.setText("Suppliers");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, -1));

        jLabel11.setFont(new java.awt.Font("Dubai Medium", 0, 18)); // NOI18N
        jLabel11.setText("Laporan");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, -1, -1));

        date2.setFont(new java.awt.Font("Dubai Medium", 0, 16)); // NOI18N
        date2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        date2.setToolTipText("");
        date2.setBorder(null);
        date2.setCaretColor(new java.awt.Color(255, 255, 255));
        date2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        date2.setEnabled(false);
        date2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date2ActionPerformed(evt);
            }
        });
        jPanel2.add(date2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, 130, 40));

        jPanel3.setBackground(new java.awt.Color(0, 0, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Dubai Medium", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Pelanggan :");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, -1, -1));

        jLabel16.setFont(new java.awt.Font("Dubai Medium", 0, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Total Transaksi :");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel17.setFont(new java.awt.Font("Dubai Medium", 0, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Jenis Barang :");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, -1, -1));

        date1.setFont(new java.awt.Font("Dubai Medium", 1, 48)); // NOI18N
        date1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        date1.setText("15");
        date1.setToolTipText("");
        date1.setBorder(null);
        date1.setCaretColor(new java.awt.Color(255, 255, 255));
        date1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        date1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date1ActionPerformed(evt);
            }
        });
        jPanel3.add(date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, 230, 90));

        date3.setFont(new java.awt.Font("Dubai Medium", 1, 48)); // NOI18N
        date3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        date3.setText("43");
        date3.setToolTipText("");
        date3.setBorder(null);
        date3.setCaretColor(new java.awt.Color(255, 255, 255));
        date3.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        date3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date3ActionPerformed(evt);
            }
        });
        jPanel3.add(date3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 230, 90));

        date4.setFont(new java.awt.Font("Dubai Medium", 1, 48)); // NOI18N
        date4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        date4.setText("23");
        date4.setToolTipText("");
        date4.setBorder(null);
        date4.setCaretColor(new java.awt.Color(255, 255, 255));
        date4.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        date4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date4ActionPerformed(evt);
            }
        });
        jPanel3.add(date4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 230, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateActionPerformed

    private void date1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date1ActionPerformed

    private void date2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date2ActionPerformed

    private void date3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date3ActionPerformed

    private void date4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbarang;
    private javax.swing.JButton btnkasir;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnreport;
    private javax.swing.JButton btnsuppliers;
    private javax.swing.JButton btnuser;
    private javax.swing.JTextField date;
    private javax.swing.JTextField date1;
    private javax.swing.JTextField date2;
    private javax.swing.JTextField date3;
    private javax.swing.JTextField date4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
