/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author LENOVO
 */
public class Kasir extends javax.swing.JFrame {

    /**
     * Creates new form Kasir
     */
    public Kasir() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        atas = new javax.swing.JPanel();
        judul = new javax.swing.JLabel();
        txtgrandtotal2 = new javax.swing.JTextField();
        tengah = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        search = new javax.swing.JLabel();
        neww = new javax.swing.JLabel();
        save = new javax.swing.JLabel();
        delete = new javax.swing.JLabel();
        cancel = new javax.swing.JLabel();
        kodebarang = new javax.swing.JLabel();
        txtkodebarang = new javax.swing.JTextField();
        namabarang = new javax.swing.JLabel();
        txtnamabarang = new javax.swing.JTextField();
        jumlahbarang = new javax.swing.JLabel();
        txtjumlahbarang = new javax.swing.JTextField();
        bawah = new javax.swing.JPanel();
        nofaktur = new javax.swing.JLabel();
        txtnofaktur = new javax.swing.JTextField();
        idpelanggan = new javax.swing.JLabel();
        txtidpelanggan = new javax.swing.JTextField();
        namapelanggan = new javax.swing.JLabel();
        txtnamapelanggan = new javax.swing.JTextField();
        subtotal = new javax.swing.JLabel();
        txtsubtotal = new javax.swing.JTextField();
        diskon = new javax.swing.JLabel();
        txtdiskon = new javax.swing.JTextField();
        grandtotal = new javax.swing.JLabel();
        txtgrandtotal1 = new javax.swing.JTextField();
        bayar = new javax.swing.JLabel();
        txtbayar = new javax.swing.JTextField();
        kembali = new javax.swing.JLabel();
        txtkembali = new javax.swing.JTextField();
        btnsimpan = new javax.swing.JButton();
        simpan = new javax.swing.JLabel();
        btncetak = new javax.swing.JButton();
        cetak = new javax.swing.JLabel();
        btnreset = new javax.swing.JButton();
        reset = new javax.swing.JLabel();
        btnkembali = new javax.swing.JButton();
        kembalii = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        atas.setBackground(new java.awt.Color(0, 0, 102));
        atas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        judul.setFont(new java.awt.Font("GeoSlab703 MdCn BT", 1, 60)); // NOI18N
        judul.setForeground(new java.awt.Color(255, 255, 255));
        judul.setText("Toko Bu Kasan");
        atas.add(judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        txtgrandtotal2.setEditable(false);
        txtgrandtotal2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        txtgrandtotal2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtgrandtotal2.setText("119000");
        txtgrandtotal2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 204, 255), new java.awt.Color(0, 0, 102)));
        txtgrandtotal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgrandtotal2ActionPerformed(evt);
            }
        });
        atas.add(txtgrandtotal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 20, 310, 60));

        tengah.setBackground(new java.awt.Color(255, 255, 255));
        tengah.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabel.setForeground(new java.awt.Color(0, 0, 102));
        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode Barang", "Nama barang", "Harga Barang", "Jumlah Barang", "Total"
            }
        ));
        tabel.setGridColor(new java.awt.Color(153, 204, 255));
        tabel.setRowHeight(20);
        jScrollPane1.setViewportView(tabel);

        tengah.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 330));

        search.setForeground(new java.awt.Color(51, 0, 102));
        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_search_40px.png"))); // NOI18N
        search.setText("Cari");
        search.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 204, 255), new java.awt.Color(0, 0, 102)));
        search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tengah.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, 90, 50));

        neww.setForeground(new java.awt.Color(51, 0, 102));
        neww.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_new_copy_40px.png"))); // NOI18N
        neww.setText("Baru");
        neww.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 204, 255), new java.awt.Color(0, 0, 102)));
        neww.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tengah.add(neww, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 350, 90, 50));

        save.setForeground(new java.awt.Color(51, 0, 102));
        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_save_40px.png"))); // NOI18N
        save.setText("Simpan");
        save.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 204, 255), new java.awt.Color(0, 0, 102)));
        save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tengah.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 350, 110, 50));

        delete.setForeground(new java.awt.Color(51, 0, 102));
        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_multiply_40px.png"))); // NOI18N
        delete.setText("Hapus");
        delete.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 204, 255), new java.awt.Color(0, 0, 102)));
        delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tengah.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 350, 100, 50));

        cancel.setForeground(new java.awt.Color(51, 0, 102));
        cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_cancel_40px.png"))); // NOI18N
        cancel.setText("Batal");
        cancel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 204, 255), new java.awt.Color(0, 0, 102)));
        cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tengah.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 350, 90, 50));

        kodebarang.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        kodebarang.setForeground(new java.awt.Color(0, 0, 102));
        kodebarang.setText("Kode Barang");
        tengah.add(kodebarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        txtkodebarang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtkodebarang.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtkodebarang.setText("ES021");
        txtkodebarang.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 204, 255), new java.awt.Color(0, 0, 102)));
        tengah.add(txtkodebarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 190, 30));

        namabarang.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        namabarang.setForeground(new java.awt.Color(0, 0, 102));
        namabarang.setText("Nama Barang");
        tengah.add(namabarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, -1, -1));

        txtnamabarang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtnamabarang.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtnamabarang.setText("Milo");
        txtnamabarang.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 204, 255), new java.awt.Color(0, 0, 102)));
        tengah.add(txtnamabarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 190, 30));

        jumlahbarang.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jumlahbarang.setForeground(new java.awt.Color(0, 0, 102));
        jumlahbarang.setText("Jumlah Barang");
        tengah.add(jumlahbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, -1, -1));

        txtjumlahbarang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtjumlahbarang.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtjumlahbarang.setText("12");
        txtjumlahbarang.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 204, 255), new java.awt.Color(0, 0, 102)));
        tengah.add(txtjumlahbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, 130, 30));

        bawah.setBackground(new java.awt.Color(153, 204, 255));
        bawah.setForeground(new java.awt.Color(153, 204, 255));
        bawah.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nofaktur.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        nofaktur.setForeground(new java.awt.Color(0, 0, 102));
        nofaktur.setText("No. Faktur");
        bawah.add(nofaktur, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        txtnofaktur.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtnofaktur.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtnofaktur.setText("3232");
        txtnofaktur.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 204, 255), new java.awt.Color(0, 0, 102)));
        bawah.add(txtnofaktur, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 190, 30));

        idpelanggan.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        idpelanggan.setForeground(new java.awt.Color(0, 0, 102));
        idpelanggan.setText("ID Pelanggan");
        bawah.add(idpelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        txtidpelanggan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtidpelanggan.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtidpelanggan.setText("09382");
        txtidpelanggan.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 204, 255), new java.awt.Color(0, 0, 102)));
        bawah.add(txtidpelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 190, 30));

        namapelanggan.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        namapelanggan.setForeground(new java.awt.Color(0, 0, 102));
        namapelanggan.setText("Nama Pelanggan");
        bawah.add(namapelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        txtnamapelanggan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtnamapelanggan.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtnamapelanggan.setText("Enrique");
        txtnamapelanggan.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 204, 255), new java.awt.Color(0, 0, 102)));
        bawah.add(txtnamapelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 190, 30));

        subtotal.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        subtotal.setForeground(new java.awt.Color(0, 0, 102));
        subtotal.setText("Sub Total");
        bawah.add(subtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        txtsubtotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtsubtotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtsubtotal.setText("115000");
        txtsubtotal.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 204, 255), new java.awt.Color(0, 0, 102)));
        bawah.add(txtsubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 190, 30));

        diskon.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        diskon.setForeground(new java.awt.Color(0, 0, 102));
        diskon.setText("Diskon (%)");
        bawah.add(diskon, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, -1, -1));

        txtdiskon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtdiskon.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtdiskon.setText("2%");
        txtdiskon.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 204, 255), new java.awt.Color(0, 0, 102)));
        bawah.add(txtdiskon, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 190, 30));

        grandtotal.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        grandtotal.setForeground(new java.awt.Color(0, 0, 102));
        grandtotal.setText("Grand Total");
        bawah.add(grandtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, -1, -1));

        txtgrandtotal1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtgrandtotal1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtgrandtotal1.setText("115000");
        txtgrandtotal1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 204, 255), new java.awt.Color(0, 0, 102)));
        bawah.add(txtgrandtotal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 190, 30));

        bayar.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        bayar.setForeground(new java.awt.Color(0, 0, 102));
        bayar.setText("Bayar");
        bawah.add(bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, -1, -1));

        txtbayar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtbayar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtbayar.setText("120000");
        txtbayar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 204, 255), new java.awt.Color(0, 0, 102)));
        bawah.add(txtbayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 130, 30));

        kembali.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        kembali.setForeground(new java.awt.Color(0, 0, 102));
        kembali.setText("Kembali");
        bawah.add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, -1, -1));

        txtkembali.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtkembali.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtkembali.setText("5000");
        txtkembali.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 204, 255), new java.awt.Color(0, 0, 102)));
        bawah.add(txtkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 130, 30));

        btnsimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_save_as_60px.png"))); // NOI18N
        btnsimpan.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 102), null));
        btnsimpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsimpan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bawah.add(btnsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, 90, 70));

        simpan.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        simpan.setForeground(new java.awt.Color(0, 0, 102));
        simpan.setText("Simpan");
        bawah.add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 90, -1, -1));

        btncetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_print_60px.png"))); // NOI18N
        btncetak.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 102), null));
        btncetak.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncetak.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bawah.add(btncetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 20, 90, 70));

        cetak.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        cetak.setForeground(new java.awt.Color(0, 0, 102));
        cetak.setText("Cetak");
        bawah.add(cetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 90, -1, -1));

        btnreset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_restart_60px.png"))); // NOI18N
        btnreset.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 102), null));
        btnreset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnreset.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bawah.add(btnreset, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 20, 90, 70));

        reset.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        reset.setForeground(new java.awt.Color(0, 0, 102));
        reset.setText("Reset");
        bawah.add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 90, -1, -1));

        btnkembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_back_60px.png"))); // NOI18N
        btnkembali.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 102), null));
        btnkembali.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnkembali.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bawah.add(btnkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 20, 90, 70));

        kembalii.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        kembalii.setForeground(new java.awt.Color(0, 0, 102));
        kembalii.setText("Kembali");
        bawah.add(kembalii, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 90, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(atas, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bawah, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(tengah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(atas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 421, Short.MAX_VALUE)
                .addComponent(bawah, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(101, 101, 101)
                    .addComponent(tengah, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(195, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtgrandtotal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgrandtotal2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgrandtotal2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kasir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel atas;
    private javax.swing.JPanel bawah;
    private javax.swing.JLabel bayar;
    private javax.swing.JButton btncetak;
    private javax.swing.JButton btnkembali;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JLabel cancel;
    private javax.swing.JLabel cetak;
    private javax.swing.JLabel delete;
    private javax.swing.JLabel diskon;
    private javax.swing.JLabel grandtotal;
    private javax.swing.JLabel idpelanggan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel judul;
    private javax.swing.JLabel jumlahbarang;
    private javax.swing.JLabel kembali;
    private javax.swing.JLabel kembalii;
    private javax.swing.JLabel kodebarang;
    private javax.swing.JLabel namabarang;
    private javax.swing.JLabel namapelanggan;
    private javax.swing.JLabel neww;
    private javax.swing.JLabel nofaktur;
    private javax.swing.JLabel reset;
    private javax.swing.JLabel save;
    private javax.swing.JLabel search;
    private javax.swing.JLabel simpan;
    private javax.swing.JLabel subtotal;
    private javax.swing.JTable tabel;
    private javax.swing.JPanel tengah;
    private javax.swing.JTextField txtbayar;
    private javax.swing.JTextField txtdiskon;
    private javax.swing.JTextField txtgrandtotal1;
    private javax.swing.JTextField txtgrandtotal2;
    private javax.swing.JTextField txtidpelanggan;
    private javax.swing.JTextField txtjumlahbarang;
    private javax.swing.JTextField txtkembali;
    private javax.swing.JTextField txtkodebarang;
    private javax.swing.JTextField txtnamabarang;
    private javax.swing.JTextField txtnamapelanggan;
    private javax.swing.JTextField txtnofaktur;
    private javax.swing.JTextField txtsubtotal;
    // End of variables declaration//GEN-END:variables
}
