/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;

/**
 *
 * @author LENOVO
 */
public class MenuUtama extends javax.swing.JFrame {
    
    public void date (){
        Date ys = new Date();
        SimpleDateFormat s = new SimpleDateFormat("EEEEE, dd MM yyyy");
        date.setText(s.format(ys)); 
    }
    
    public MenuUtama() {
        initComponents();
        date();
        setLocationRelativeTo(this);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Profil = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        btnuser = new javax.swing.JButton();
        btnbarang = new javax.swing.JButton();
        btnkasir = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        btnreport = new javax.swing.JButton();
        btnsuppliers = new javax.swing.JButton();
        user = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        barang = new javax.swing.JLabel();
        kasir = new javax.swing.JLabel();
        suppliers = new javax.swing.JLabel();
        laporan = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        Total = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        date1 = new javax.swing.JTextField();
        date3 = new javax.swing.JTextField();
        date4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Profil.setBackground(new java.awt.Color(153, 204, 255));
        Profil.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_NFT_User_120px.png"))); // NOI18N
        Profil.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dubai Medium", 2, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Owner");
        Profil.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, -1));

        jLabel12.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Inventory And Management");
        Profil.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 210, 50));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_management_120px_3.png"))); // NOI18N
        Profil.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 120, 120));

        jLabel14.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("I  M  A  N");
        Profil.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 150, 50));

        jLabel15.setFont(new java.awt.Font("Dubai Medium", 0, 25)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Marzuki Akmal");
        Profil.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        Menu.setBackground(new java.awt.Color(255, 255, 255));
        Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnuser.setBackground(new java.awt.Color(255, 255, 255));
        btnuser.setForeground(new java.awt.Color(255, 255, 255));
        btnuser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_user_folder_120px.png"))); // NOI18N
        btnuser.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 204, 255), new java.awt.Color(153, 204, 255)));
        btnuser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnuser.setOpaque(false);
        Menu.add(btnuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 140, 120));

        btnbarang.setBackground(new java.awt.Color(255, 255, 255));
        btnbarang.setForeground(new java.awt.Color(255, 255, 255));
        btnbarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_shop_120px.png"))); // NOI18N
        btnbarang.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 204, 255), new java.awt.Color(153, 204, 255)));
        btnbarang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnbarang.setOpaque(false);
        Menu.add(btnbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 140, 120));

        btnkasir.setBackground(new java.awt.Color(255, 255, 255));
        btnkasir.setForeground(new java.awt.Color(255, 255, 255));
        btnkasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_paper_money_120px.png"))); // NOI18N
        btnkasir.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 204, 255), new java.awt.Color(153, 204, 255)));
        btnkasir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnkasir.setOpaque(false);
        btnkasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkasirActionPerformed(evt);
            }
        });
        Menu.add(btnkasir, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 140, 120));

        btnlogout.setBackground(new java.awt.Color(255, 255, 255));
        btnlogout.setForeground(new java.awt.Color(255, 255, 255));
        btnlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_exit_120px.png"))); // NOI18N
        btnlogout.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 204, 255), new java.awt.Color(153, 204, 255)));
        btnlogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlogout.setOpaque(false);
        Menu.add(btnlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 140, 120));

        btnreport.setBackground(new java.awt.Color(255, 255, 255));
        btnreport.setForeground(new java.awt.Color(255, 255, 255));
        btnreport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_graph_report_120px.png"))); // NOI18N
        btnreport.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 204, 255), new java.awt.Color(153, 204, 255)));
        btnreport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnreport.setOpaque(false);
        Menu.add(btnreport, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 140, 120));

        btnsuppliers.setBackground(new java.awt.Color(255, 255, 255));
        btnsuppliers.setForeground(new java.awt.Color(255, 255, 255));
        btnsuppliers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_supplier_120px.png"))); // NOI18N
        btnsuppliers.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 204, 255), new java.awt.Color(153, 204, 255)));
        btnsuppliers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsuppliers.setOpaque(false);
        Menu.add(btnsuppliers, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 140, 120));

        user.setFont(new java.awt.Font("Dubai Medium", 0, 18)); // NOI18N
        user.setText("User");
        Menu.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, -1, -1));

        logout.setFont(new java.awt.Font("Dubai Medium", 0, 18)); // NOI18N
        logout.setText("Logout");
        Menu.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 320, -1, -1));

        barang.setFont(new java.awt.Font("Dubai Medium", 0, 18)); // NOI18N
        barang.setText("Barang");
        Menu.add(barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, -1, -1));

        kasir.setFont(new java.awt.Font("Dubai Medium", 0, 18)); // NOI18N
        kasir.setText("Kasir");
        Menu.add(kasir, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));

        suppliers.setFont(new java.awt.Font("Dubai Medium", 0, 18)); // NOI18N
        suppliers.setText("Suppliers");
        Menu.add(suppliers, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, -1));

        laporan.setFont(new java.awt.Font("Dubai Medium", 0, 18)); // NOI18N
        laporan.setText("Laporan");
        Menu.add(laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, -1, -1));

        date.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        date.setEnabled(false);
        Menu.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 260, 30));

        Total.setBackground(new java.awt.Color(0, 0, 102));
        Total.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Dubai Medium", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Pelanggan :");
        Total.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, -1, -1));

        jLabel16.setFont(new java.awt.Font("Dubai Medium", 0, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Total Transaksi :");
        Total.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel17.setFont(new java.awt.Font("Dubai Medium", 0, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Jenis Barang :");
        Total.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, -1, -1));

        date1.setFont(new java.awt.Font("Dubai Medium", 1, 48)); // NOI18N
        date1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        date1.setText("15");
        date1.setToolTipText("");
        date1.setBorder(null);
        date1.setCaretColor(new java.awt.Color(255, 255, 255));
        date1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        date1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date1ActionPerformed(evt);
            }
        });
        Total.add(date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, 230, 90));

        date3.setFont(new java.awt.Font("Dubai Medium", 1, 48)); // NOI18N
        date3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        date3.setText("43");
        date3.setToolTipText("");
        date3.setBorder(null);
        date3.setCaretColor(new java.awt.Color(255, 255, 255));
        date3.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        date3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date3ActionPerformed(evt);
            }
        });
        Total.add(date3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 230, 90));

        date4.setFont(new java.awt.Font("Dubai Medium", 1, 48)); // NOI18N
        date4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        date4.setText("23");
        date4.setToolTipText("");
        date4.setBorder(null);
        date4.setCaretColor(new java.awt.Color(255, 255, 255));
        date4.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        date4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date4ActionPerformed(evt);
            }
        });
        Total.add(date4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 230, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Profil, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, 733, Short.MAX_VALUE)
                    .addComponent(Total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Profil, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1)
                .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void date1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date1ActionPerformed

    private void date3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date3ActionPerformed

    private void date4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date4ActionPerformed

    private void btnkasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkasirActionPerformed
        Kasir kasir = new Kasir();
        kasir.setVisible(true);
    }//GEN-LAST:event_btnkasirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel Profil;
    private javax.swing.JPanel Total;
    private javax.swing.JLabel barang;
    private javax.swing.JButton btnbarang;
    private javax.swing.JButton btnkasir;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnreport;
    private javax.swing.JButton btnsuppliers;
    private javax.swing.JButton btnuser;
    private javax.swing.JLabel date;
    private javax.swing.JTextField date1;
    private javax.swing.JTextField date3;
    private javax.swing.JTextField date4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel kasir;
    private javax.swing.JLabel laporan;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel suppliers;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
